### ISSUE TITLE
Good scroll prevents moving the cursor left and right in evil-mode

### ISSUE THREAD

**Issue by JordanAnthonyKing** [io12/good-scroll.el#16] opened 2021-04-19 15:45 UTC
Enabling `good-scroll-mode` breaks moving the cursor left or right in evil-mode, either by the hl or arrow keys. A message is given of: `Args out of range: 1, 3642`. This doesn't prevent cursor movement with the arrow-keys in insert-mode.

Disabling `good-scroll-mode` again fixes the issue.

I'm running Doom on gccemacs.

**Comment by io12** [comment] 2021-04-20 00:53
I can't reproduce this with regular Emacs 27.2 (not gccemacs). I'll try with gccemacs later, but just out of curiosity, does setting `good-scroll-avoid-vscroll-reset` to `nil` fix this?

**Comment by JordanAnthonyKing** [comment] 2021-04-20 09:53
>out of curiosity, does setting `good-scroll-avoid-vscroll-reset` to `nil` fix this?
It does!

**Comment by io12** [comment] 2021-04-20 10:51
I just tested with gccemacs+pgtk and can reproduce the issue. Because it only reproduces on certain Emacs versions, this might be an Emacs bug. The error happens in `line-number-at-pos` in `good-scroll--point-at-top-p` in `good-scroll--advice-line-move`, which explains why disabling `good-scroll-avoid-vscroll-reset` fixes it. I haven't looked into this enough to know if it's native-comp's fault or pgtk's fault though, or why the error happens.

**Comment by JordanAnthonyKing** [comment] 2021-04-20 11:15
I don't believe I compiled with pgtk:
```
features     CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ IMAGEMAGICK JPEG JSON LCMS2 LIBSELINUX LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB
```

**Comment by thornjad** [comment] 2021-04-27 16:42
I've run into the same issue on Emacs' latest `master`, which gccemacs (native-comp) has now been merged into. Disabling `good-scroll-avoid-vscroll-reset` also fixes the error for me. I'd just like to add that I noticed that (with that var set to `t`), if `(point)` is at 0, `evil-forward-char` does not error, and at pos 1, `evil-backward-char` does not error. In other words, I can move back and forth between the first two chars without error, but starting from any other position does error.

I do also notice that `evil-forward-char` and `evil-backward-char` narrow the buffer before actually doing the move, and I know that `line-number-at-pos` behaves differently when the buffer is narrowed.

I don't have time to look into it further than that at the moment, but thought I'd throw in some info I found while debugging the error. Evil tries to swallow up the error, so it took me a bit to even realize it came from good-scroll.

**Comment by io12** [comment] 2021-05-20 00:04
At this point, I'm pretty sure it's an upstream Emacs bug since `line-number-at-pos` was moved from elisp to C between the latest Emacs release 27.2 and `master`. I [commented](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=22763#103) on the bug tracker with what I think the bug is.

**Comment by io12** [comment] 2021-05-21 07:45
Turns out the *old* `line-number-at-pos` behavior was an Emacs bug, and fixing the bug with the rewrite in C triggered a bug in good-scroll. I think I can fix this by just temporarily widening before calling `line-number-at-pos`.

**Closed** 2021-05-21 07:46 UTC
Labels: bug
